import { appendActivityEvent } from "@/lib/activity-store";
import { writeJsonFile } from "@/lib/data";
import { makeId } from "@/lib/model-utils";
import { readTasks } from "@/lib/task-store";
import { Task } from "@/lib/types";
import { NextResponse } from "next/server";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

type ControlAction =
  | "create_demo_task"
  | "advance_task"
  | "emit_cron_event"
  | "toggle_agent";

function taskTransition(column: Task["column"]): Task["column"] {
  if (column === "todo") {
    return "in_progress";
  }
  if (column === "in_progress") {
    return "review";
  }
  return "done";
}

export async function POST(request: Request) {
  const body = (await request.json().catch(() => null)) as
    | { action?: string; agentId?: string }
    | null;

  if (!body || !body.action) {
    return NextResponse.json(
      { error: "Missing action in payload." },
      { status: 400 },
    );
  }

  const action = body.action as ControlAction;
  const now = new Date().toISOString();
  const agentId = body.agentId?.trim() || "main";

  if (action === "emit_cron_event") {
    const event = await appendActivityEvent({
      actorId: "main",
      kind: "cron",
      message: "Manual cron wake triggered from Control Panel.",
      metadata: { source: "control-panel" },
      source: "local",
    });
    return NextResponse.json({ ok: true, action, event });
  }

  const tasks = await readTasks();

  if (action === "create_demo_task") {
    const task: Task = {
      id: makeId("task"),
      title: `Demo task ${new Date().toLocaleTimeString("en-US", { hour12: false })}`,
      description: "Created from Control Panel to validate live board updates.",
      column: "todo",
      priority: "medium",
      assigneeId: agentId,
      projectId: null,
      createdAt: now,
      updatedAt: now,
      source: "local",
    };

    await writeJsonFile("tasks.json", [task, ...tasks]);
    await appendActivityEvent({
      actorId: task.assigneeId,
      kind: "task",
      message: `Control created task "${task.title}"`,
      metadata: { taskId: task.id, column: task.column },
      source: "local",
    });
    return NextResponse.json({ ok: true, action, task });
  }

  if (action === "advance_task") {
    const index = tasks.findIndex((task) => task.column !== "done");
    if (index < 0) {
      return NextResponse.json(
        { error: "No non-done task available to advance." },
        { status: 409 },
      );
    }

    const current = tasks[index];
    const next = {
      ...current,
      column: taskTransition(current.column),
      updatedAt: now,
      source: "local" as const,
    };
    const updated = [...tasks];
    updated[index] = next;

    await writeJsonFile("tasks.json", updated);
    await appendActivityEvent({
      actorId: next.assigneeId,
      kind: "task",
      message: `Control advanced "${next.title}" to ${next.column}`,
      metadata: { taskId: next.id, column: next.column },
      source: "local",
    });

    return NextResponse.json({ ok: true, action, task: next });
  }

  if (action === "toggle_agent") {
    const activeIndex = tasks.findIndex(
      (task) => task.assigneeId === agentId && task.column === "in_progress",
    );

    if (activeIndex >= 0) {
      const activeTask = tasks[activeIndex];
      const next = {
        ...activeTask,
        column: "review" as const,
        updatedAt: now,
        source: "local" as const,
      };
      const updated = [...tasks];
      updated[activeIndex] = next;
      await writeJsonFile("tasks.json", updated);
      await appendActivityEvent({
        actorId: agentId,
        kind: "system",
        message: `${agentId} toggled to idle (task moved to review).`,
        metadata: { taskId: next.id },
        source: "local",
      });
      return NextResponse.json({ ok: true, action, mode: "idle", task: next });
    }

    const task: Task = {
      id: makeId("task"),
      title: `Live session for ${agentId}`,
      description: "Generated by Control Panel toggle to simulate active work.",
      column: "in_progress",
      priority: "medium",
      assigneeId: agentId,
      projectId: null,
      createdAt: now,
      updatedAt: now,
      source: "local",
    };
    await writeJsonFile("tasks.json", [task, ...tasks]);
    await appendActivityEvent({
      actorId: agentId,
      kind: "system",
      message: `${agentId} toggled to active (new in-progress task).`,
      metadata: { taskId: task.id },
      source: "local",
    });
    return NextResponse.json({ ok: true, action, mode: "active", task });
  }

  return NextResponse.json({ error: "Unknown action." }, { status: 400 });
}

